-- DOPPAN uses the shared score/ranking RPCs with a dedicated active game row.
insert into public.games (
  game_slug,
  title,
  game_url,
  description,
  share_text,
  score_order,
  score_unit,
  is_active,
  score_scale,
  score_decimals,
  score_label,
  first_score_label,
  best_score_label,
  top_ranking_type,
  submission_mode
) values (
  'doppan',
  'DOPPAN',
  'https://chameleonjp-lab.github.io/doppan/',
  '球を打ち返して戻り道をつなぎ直す3球ピンボール',
  'DOPPANで戻り道をつなぎ直しました',
  'desc',
  '点',
  true,
  1,
  0,
  'スコア',
  '初回スコア',
  '最高スコア',
  'best',
  'shared'
)
on conflict (game_slug) do update set
  title = excluded.title,
  game_url = excluded.game_url,
  description = excluded.description,
  share_text = excluded.share_text,
  score_order = excluded.score_order,
  score_unit = excluded.score_unit,
  is_active = excluded.is_active,
  score_scale = excluded.score_scale,
  score_decimals = excluded.score_decimals,
  score_label = excluded.score_label,
  first_score_label = excluded.first_score_label,
  best_score_label = excluded.best_score_label,
  top_ranking_type = excluded.top_ranking_type,
  submission_mode = excluded.submission_mode;
